### ISSUE TITLE
pretrain_struc can't be run

### ISSUE THREAD

**Issue by Filco306** [genggengcss/OntoZSL#3]
Hello, 

I am trying to run your model, but it is not working. When I try to follow your instructions, I get the following error: 

```bash
>>> python code/OntoEncoder/pretrain_struc.py --dataset NELL --hidden_dim 300
Traceback (most recent call last):
  File "/.../code/OntoEncoder/pretrain_struc.py", line 18, in <module>
    from code import KGEModel
ImportError: cannot import name 'KGEModel' from 'code' (/.../lib/python3.9/code.py)
```

Running it from **any** of the folders in the repo, does not work. How do I fix this? :) 

Thank you! 

Best,
Filip

**Comment by genggengcss** [comment]
> 

Hi Filip, I am sorry for the late reply. There is a mistake on the file name. The quoted code for "KGEModel" should be "from model import KGEModel". I will revise it right now.

**Comment by genggengcss** [comment]
> Hello,
> 
> I am trying to run your model, but it is not working. When I try to follow your instructions, I get the following error:
> 
> ```shell
> >>> python code/OntoEncoder/pretrain_struc.py --dataset NELL --hidden_dim 300
> Traceback (most recent call last):
>   File "/.../code/OntoEncoder/pretrain_struc.py", line 18, in <module>
>     from code import KGEModel
> ImportError: cannot import name 'KGEModel' from 'code' (/.../lib/python3.9/code.py)
> ```
> 
> Running it from **any** of the folders in the repo, does not work. How do I fix this? :)
> 
> Thank you!
> 
> Best, Filip

Hi Filip, I am sorry for the late reply. There is a mistake on the file name. The quoted code for "KGEModel" should be "from model import KGEModel". I will revise it right now.
